### ISSUE TITLE
Dynamic shape size

### ISSUE THREAD

**Issue by uppalavamsi** [NationalSecurityAgency/qgis-shapetools-plugin#10]
Could there be a possibility of having shape sized to their relative density to the objects around, such that visibility is good. Such that shapes would not overlay but have better visibility when zoomed out.

![image](https://user-images.githubusercontent.com/38352200/38769544-5ad1abae-4022-11e8-915c-2cb65f73b2d7.png)

**Comment by uppalavamsi** [comment]
Got this going with small tweak, by just re-arranging data in descending order

![image](https://user-images.githubusercontent.com/38352200/38769574-c37365a8-4022-11e8-8fa7-d9778780ba47.png)

However it could be better to give users on-the-go option to do it so from tool level.

**Comment by hamiltoncj** [comment]
@uppalavamsi One thing I never thought about is the possibility to have the shapes as a style. Then it could be more dynamic. I don't know if this is a possibility, but I will check into it.

**Comment by uppalavamsi** [comment]
Hi Hamilton,

Of late was was reading about this feature coming in QGIS 3. Yet to explore
the details. Would check some online material and identify the features.

It is like when we zoom out per se Google map major city name keep visible
at all zoom levels to the ease of user readability.

This function would help Telecom engineer to optimize site with KPIs in
comparison with its neighbours. This scenarios arrises with sites which are
designed for rural, rail or road coverage while moving away and towards
city or town which is ticket populated with cell sites where higher the
magnitude of shape would result in overlapping and same time the spur sites
visibility is degraded for on the go verification of details.

However it could be good to have this feature at tool level, would be
checking it parallelly on QGIS.

With regards,
Vamsi
+91 98 664 68185

**Comment by hamiltoncj** [comment]
I'm going to close this. Since Shape Tools create physical shapes, this request is not possible. Perhaps it could be done with styling, but that is outside the scope of Shape Tools.
