### ISSUE TITLE
Extremely long processing time

### ISSUE THREAD

**Issue by uppalavamsi** [NationalSecurityAgency/qgis-shapetools-plugin#12]
Tool is taking extremely longer duration to create desired output. It is takings minutes to generate shapes of ~25,000.

However it is a matter of few seconds(<5 sec) to create about 250,000 "Pie Wedges" when we use some other Python script, but it has limitation to create multi sized shape in one go.

Please have this process time check and optimize to have better tool usability.

**Comment by hamiltoncj** [comment]
@uppalavamsi Thank you for taking the time to offer all these suggestions. This is what helps drive the development of tools and I find such suggestions very useful.

ShapeTools is using geodesic math for all its calculations and I am using a python library for it. This may be part of the slowness, but I will investigate to see if there are speed improvements that I can implement. 

Thanks once again.

**Comment by hamiltoncj** [comment]
@uppalavamsi Do you have an example of a tool that is fast? I am guessing that most tools are not doing geodesic calculations which takes more time, but I'm sure there are some optimizations that I can do.

Thanks

**Comment by uppalavamsi** [comment]
Hi Hamilton,

First we have to say thanks a million that you made this tool, which by its
name we could not able to find on libraries for so long. This would be for
sure help Telecom industry a lot for betterment, taking the capability and
flexibility of Tool.

Thanks for very open approach of receiving inputs, Ive put this to the tool
which of non distribution has made ~30 k sites of 108 k cells just at the
blink into WKT in CSV file, then however tool has couple of sec to plot the
polygons.

I was wondering for past 1 year attempt pulling online Turtle code but not
able to make it work and enquiring every friend i have in IT field to help
do some code to release a plugin for QGIS which would eventually help
several in Telecom. Or pay 200USD to get the code from small firm i know
but they are new to Python hence still persuing, Lucky got it now... Guess
I could not do it now!

Seek your help if possible to publish Plugin with at least 2 to 3 Telecom
related tags in narration, such that it would reach many:

1. Telecom site
2. Cell Site
3. Cell Sector maker

With this plugin's help we could able to share atleast few Telecom MOPs on
online now.

With regards,
Vamsi
+91 98 664 68185

**Comment by hamiltoncj** [comment]
@uppalavamsi I have made a slight change with the Shape Tools pie shape. You can now specify the number of degrees before another point is added in the arc of the pie. Originally, I set that to 4. I now have it set by default to 6, but you can enter another number. The larger the number the faster it will be, but the quality of the arc will go down.

The geodesic calculations takes time. If the map layer is not a geographic coordinate system and the distances are small then I could consider just doing geometric calculations. That could speed up calculations even more.

This addition is in the QGIS 3.0.5 version.

**Comment by hamiltoncj** [comment]
I'm going to close this because I don't know of anything more I can do. I have been able to get some speed improvements. Geodesic calculations are slower than euclidean calculations, but this plugin is about geodesic. If the QGIS team were to include some of these capability into the core then there could be more improvements.
