### ISSUE TITLE
CRS Selection

### ISSUE THREAD

**Issue by idmurp** [NationalSecurityAgency/qgis-shapetools-plugin#14]
I have a number of users hitting issues sometimes with the CRS detailing to 4326, we don't use otf as standard as it confuses people.  Is it possible to include a crs selection in future versions?

Brilliant tool though!

**Comment by hamiltoncj** [comment]
@idmurp Thank you for your suggestion. I have actually been thinking about doing this as well. Look for it in the next release.

**Comment by hamiltoncj** [comment]
@idmurp I just updated the QGIS 3.0 version and added CRS selection to the "Create Shapes" function. It is now in the QGIS plugin repo although it may take a few minutes for the repo to report that it is there. Do you need the capability for QGIS 2.x as well?

**Comment by idmurp** [comment]
Hi

I can advise the users needing this to upgrade to use QGIS 3 for this
particular function.  Thanks very much

Ian

On 24 May 2018 10:15 pm, "C Hamilton" <notifications@github.com> wrote:

@idmurp <https://github.com/idmurp> I just updated the QGIS 3.0 version and
added CRS selection to the "Create Shapes" function. It is now in the QGIS
plugin repo although it may take a few minutes for the repo to report that
it is there. Do you need the capability for QGIS 2.x as well?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NationalSecurityAgency/qgis-shapetools-plugin/issues/14#issuecomment-391865097>,
or mute the thread

**Comment by hamiltoncj** [comment]
@idmurp I have added CRS selection to the "Create Shapes" function for the QGIS 2 plugin (0.7.8).
