### ISSUE TITLE
XY to line: layers present but lines missing upon re-open

### ISSUE THREAD

**Issue by SimonDedman** [NationalSecurityAgency/qgis-shapetools-plugin#15]
Added delimited text points layer and created line using XY to line successfully. Saved project, closed, reopened (next day) and layers still present but lines missing. Please see (boring) attachments. 
![npc streamline minmaxav](https://user-images.githubusercontent.com/4599748/40451411-626d86fa-5e93-11e8-8283-effd8068b50d.png)
![shape plugin bug](https://user-images.githubusercontent.com/4599748/40451438-77cae9ac-5e93-11e8-85a2-5e68e8ed2c59.png)

Win 10 enterprise, 
QGIS version | 3.0.3-Girona | QGIS code revision | 8a899c8758
Compiled against Qt | 5.9.2 | Running against Qt | 5.9.2
Compiled against GDAL/OGR | 2.2.4 | Running against GDAL/OGR | 2.2.4
Compiled against GEOS | 3.5.0-CAPI-1.9.0 | Running against GEOS | 3.5.0-CAPI-1.9.0 r4084
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.1
PROJ.4 Version | 493

Cheers!

**Comment by hamiltoncj** [comment]
@SimonDedman  Shape Tools uses memory layers which are not saved by default. You need to save them or install the Memory Layer Saver plugin. Perhaps I should make that more clear in the documentation.

http://plugins.qgis.org/plugins/MemoryLayerSaver/

Eventually, I plan on moving these functions to processing in which case it will give more options on how to save them.

**Comment by SimonDedman** [comment]
Hi again, for sure would be good to let users know; I didn't even know about memory layers until now!
