### ISSUE TITLE
XY to Line Layer Null After Closing QGIS Project

### ISSUE THREAD

**Issue by zionsteiner** [NationalSecurityAgency/qgis-shapetools-plugin#18]
Recently I've been having issues saving XY to line vector layers with my projects. Each xy to line layer is generated from a .csv file with origin and destination coordinates which works great initially. However, after the project has been saved, closed, and reopened, the line layer has somehow disassociated from the .csv, leaving all fields in the line layer's attribute table to read NULL. What is the proper way to make sure the layer stays intact between saving and exiting in QGIS?

**Comment by hamiltoncj** [comment]
I am assuming you are using QGIS 2.x. In that version XY to line uses memory layers which are not saved when you save a QGIS project. You have three options. 1) Download the Memory Layer Saver plugin. This will then save your memory layers. 2) Upgrade to QGIS 3. XY to Line tool has been moved to be a processing algorithm and you have many more options on how it is saved. 3) Simply save the resulting vector layer and then import it back into QGIS.

**Comment by hamiltoncj** [comment]
@zionsteiner I'm assuming that one of the above suggestions works for you. I am closing the ticket, but if you have any more problems feel free to contact us again.
