### ISSUE TITLE
Create hublines or nearest neighbours in a given direction

### ISSUE THREAD

**Issue by uppalavamsi** [NationalSecurityAgency/qgis-shapetools-plugin#19]
Hi Hamilton,

hope you are doing good. Thanks for the continued enhancements on wedget shapes, which are getting process more simpler.

We wish to have option for creation of hublines in a given direction / azimuth, illustration of the usage is given under [(https://i.stack.imgur.com/VyOpc.png)]. Which would help creation of relations between serving and target cells of telecom site. Maybe point of intersection of outward to inwards spoke/sector would be more fruitful with user definable magnitudes on backward and side lobes [https://www.electronics-notes.com/articles/antennas-propagation/antenna-theory/gain-directivity.php]

Thanks,

with regards,
vamsi

**Comment by hamiltoncj** [comment]
Vamsi,

Shape Tools has a create line of bearing tool which creates a line from a point at a given azimuth and distance. This seems to be what you are talking about with hublines. Does that do what you need? If not what more is needed?

**Comment by hamiltoncj** [comment]
@uppalavamsi Do you have anymore input on this? Does the create line tool help? I'm not sure what to do with this request and whether it would be within the scope of Shape Tools.

Thanks

**Comment by uppalavamsi** [comment]
Hi Hamilton,

Delayed response due to some issues.

Wish to have the feature in association with the lines is kNN algorithum to
identify the nearest neighbors.

And in this case we have 4 criterias:
1. Points: Start point is observer and single; proximity points are many in
the vicinity of start point

2. View angles: An imaginary pie wedge made from start and proximity points

3. Distance to the nearest neighbor: If ever the outward lines of given
View angles are intersecting each other the intersecting distance to the
nearest neighbor in ascending order with k value as 60 kms and the number
interesting points are not more than shortest ~32 nos of unique set of
intersections

**Comment by uppalavamsi** [comment]
4. Magnitude of proximity point: to rank the neighbor based on predictive
RF power factors

**Comment by hamiltoncj** [comment]
@uppalavamsi This request is really outside the scope of the Shape Tools plugin. I am currently out of the office for several weeks, but I will ask my sponsors when I get back to see if there is any interest in pursuing this. 

I am not sure how to implement it though and I think it would take me a lot of research. If you have someone that would like to work on this, it could be added to Shape Tools.

I will be back in touch in a few weeks.

**Comment by uppalavamsi** [comment]
Hi Hamilton,

Thanks so much for writing in detail. Good to hear that tool is open for
collaboration. I have no coding knowledge, however would peruse this idea
further as it has potential to address masses and ease daily workings in
telecom segment where many netwroks to see yet self organizing / automatic
neighbour addition.

**Comment by uppalavamsi** [comment]
Hi,

I'm open to contribute on sponsoring in terms of working capital for up to
200 usd (that's roughly my savings for a month).

**Comment by hamiltoncj** [comment]
@uppalavamsi I wish I could help out on this, but it is outside the scope of the Shape Tools plugin. This is getting into advanced analysis. I have asked around to see if anyone funding my QGIS development were interested in this capability and they were not interested. I don't have the time to do this on personal time. I think it could take a lot of work.

I am going to go ahead and close this ticket.
