### ISSUE TITLE
Add Circle Line

### ISSUE THREAD

**Issue by Vitruvius21** [NationalSecurityAgency/qgis-shapetools-plugin#22]
Hi @hamiltoncj, 

First of all, thank you for a such great plugin.

Regarding the topic, could you add **Circle Line** as a _Line type_? I wish to make maps like this https://www.stayaspensnowmass.com/sites/default/files/aspenFlightMap.jpg but on small areas _Geodesic_ or _Great Circle_ lines do not give proper effect.

**Comment by hamiltoncj** [comment]
@Vitruvius21 Do you know how to implement this line type? I don't know how to do it.

**Comment by Vitruvius21** [comment]
@hamiltoncj maybe [this blog-post](https://medium.com/@tomchadwin/mapping-emotion-fighting-school-closures-with-qgis-28842661bf14) will give you some ideas? Look for Curving the lines into pseudo-3D

**Comment by hamiltoncj** [comment]
This is more of a styling problem that is dependent on the projection so it is not something that I want to include in Shape Tools.
