### ISSUE TITLE
Create pie wedge failure when run from processing toolbox

### ISSUE THREAD

**Issue by aprobinson3** [NationalSecurityAgency/qgis-shapetools-plugin#23]
Hi,

Thank you so much for this plugin it really is excellent!

I am receiving the following error when Creating a pie wedge from processing toolbox, however when I use the same settings via the plugin it works fine.

**Processing algorithm…
Algorithm 'Create pie wedge' starting…
Input parameters:
{ 'Azimuth1Field' : 'Azimuth', 'Azimuth2Field' : 'Beamwidth', 'AzimuthMode' : 1, 'DefaultAzimuth1' : 0, 'DefaultAzimuth2' : 30, 'DefaultRadius' : 20, 'DrawingSegments' : 36, 'InputLayer' : 'file:///C:/Users/xxx/Documents/QGIS/Drawing%20Sectors/LTE%20Sectors.csv?type=csv&xyDms=yes&xField=Longitude&yField=Latitude&crs=EPSG:4326&spatialIndex=yes&subsetIndex=no&watchFile=no', 'OutputLayer' : 'memory:', 'RadiusField' : 'Sector Radius', 'ShapeType' : 0, 'UnitsOfMeasure' : 1 }

Traceback (most recent call last):
File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\shapetools\createPie.py", line 237, in processAlgorithm
if index % 100 == 0:
NameError: name 'index' is not defined

Execution failed after 0.03 seconds

Loading resulting layers
Algorithm 'Create pie wedge' finished**

Attached are screenshots of the settings used:

![wedge_plugin](https://user-images.githubusercontent.com/41752568/44863032-f49dd100-ac73-11e8-87e6-90c93f1ab418.png)

![wedge_proc_toolbox](https://user-images.githubusercontent.com/41752568/44863184-59f1c200-ac74-11e8-8d11-fa0da6cbaeab.png)

Thanks for your help!

**Comment by hamiltoncj** [comment]
@aprobinson3 Sorry about that. I have fixed the bug and it is in version 3.1.2. I just uploaded it to the QGIS plugin directory. It may take up to 30 minutes before they update the plugin listing.

**Comment by hamiltoncj** [comment]
@aprobinson3 It now shows up in the QGIS plugin manager.

**Comment by aprobinson3** [comment]
Thank you very much for the quick fix! I've just downloaded it and it works great!
