### ISSUE TITLE
cannot use different ellipsoid

### ISSUE THREAD

**Issue by mlqc** [NationalSecurityAgency/qgis-shapetools-plugin#29]
When I try using a Mars2000 ellipsoid (with radius=3396190), the result seems to imply it is still using the radius of the Earth. Could you help me solve that issue? thanks!

**Comment by hamiltoncj** [comment]
You are right. That is one algorithm that I did not fully integrate as a geodesic algorithm with the different ellipsoids. I will wok on it his week

**Comment by mlqc** [comment]
Great! thanks :)

**Comment by hamiltoncj** [comment]
@mlqc 
I have updated the QGIS 3 Shape Tools plugin, version 3.2.4, ellipse tool to be fully geodesic and support the different ellipsoids. Let me know if you have any problems with it. The ellipse tool is also now in the Shape Tools processing toolbox. I think I will back port this fix to the QGIS 2 plugin.

**Comment by hamiltoncj** [comment]
I am going to close this ticket as I believe the issue has been solved. If you have any other problem please let me know.
