### ISSUE TITLE
Create shapes for selected features and retain input geometries in output file

### ISSUE THREAD

**Issue by uppalavamsi** [NationalSecurityAgency/qgis-shapetools-plugin#30]
Hi Hamilton,

Happy New Year

Wish to have feature in the tool to generate shares for the selected features on the canvas

Also request to retain input geometrics (Lat Long) to the final shapes output file, which could be used for processing other activities later.

**Comment by hamiltoncj** [comment]
@uppalavamsi 
If you use the Processing shape creation algorithms then you have the option to process only selected features. My plan is to replace the "Create shapes" from the Shape Tools vector menu with a Create Shapes menu showing each individual shape from Processing. This will avoid having two versions now that I have all of the shapes ported to Processing. I have added an additional shape to Processing that is not available from the Vector menu.

For your second request, I can add the input geometry to two separate x and y fields. It might be several weeks though. I am making an update today with Shape Tools, adding in Centimeters and Inches for the Units of distance.

**Comment by hamiltoncj** [comment]
@uppalavamsi 
I made the shape creation processing only and with that you can select to only include selected features. There is now an option for each shape to include the input geometry into two fields of the output table.  Let me know how this works for you.

**Comment by uppalavamsi** [comment]
Hi Hamilton,

Thanks so much for the new enhancement could able to see this works good for our general day to day workings. It is admirable to see the turn around time in taking it up and making available with immediate support
