### ISSUE TITLE
support other language

### ISSUE THREAD

**Issue by wsk170** [NationalSecurityAgency/qgis-shapetools-plugin#31]
@hamiltoncj Hi, Thank you for your great plugin. It's very usefull. Can you add other language support? Provide i18n directory and en.ts file to translate.

**Comment by hamiltoncj** [comment]
I've known that at some point I would need to do this so thank you for your suggestion. I will look into how to do this and will provide it for the next release. If you have any further guidance please let me know.

**Comment by hamiltoncj** [comment]
@wsk170 
I'm not 100% sure I have everything correct, but there is an i18n directory with the en.ts file. I don't know how this all works especially when changes are made to the code, but you are welcome to give suggestions and prepare a translation.

**Comment by wsk170** [comment]
@hamiltoncj Thank you！And I did some research for PyQt translation and refer other QGIS plugin.
First, modify tr function's  "Processing" to "@default", because context name in ts file is "@default".
Second, add the following code to class ShapeTools __init__ method to load translation file.
```
# initialize plugin directory
self.plugin_dir = os.path.dirname(__file__)
# initialize locale
locale = QSettings().value('locale/userLocale')[0:2]
locale_path = os.path.join(
    self.plugin_dir,
    'i18n',
    'shapeTools_{}.qm'.format(locale))

if os.path.exists(locale_path):
    self.translator = QTranslator()
    self.translator.load(locale_path)
    if qVersion() > '4.3.3':
        QCoreApplication.installTranslator(self.translator)
```
I try this method, and get the translation. yes, it's chinese. and when I finish translation, i will push to github.
![image](https://user-images.githubusercontent.com/10161173/60030109-fd650500-96d4-11e9-9ffa-4292085111af.png)

**Comment by wsk170** [comment]
@hamiltoncj I have finished the chinese translation, and make a pull request. waiting for you merge it.

**Comment by hamiltoncj** [comment]
@wsk170 
I have made a number of updates. Can you check to make sure it works properly for you and if it does I will push out a new release.

Thanks!

**Comment by wsk170** [comment]
@hamiltoncj I try it, and create a pull to load the right translation. you could merge it.

**Comment by hamiltoncj** [comment]
I did the merge. Does it work correctly now?

**Comment by wsk170** [comment]
Yes, it worked correctly. Thank your for your great work.

**Comment by hamiltoncj** [comment]
Thank you with helping to set up translation in Shape Tools.
