### ISSUE TITLE
Plug-In installation not working

### ISSUE THREAD

**Issue by GeoN5ON** [NationalSecurityAgency/qgis-shapetools-plugin#35]
Hello,

somehow the plug-in installation in QGIS 3 is not working.

Best

Nilz

**Comment by hamiltoncj** [comment]
You will need to give me some more information. Shape Tools is being used by thousands of users and they have not had a problem with installation so lets see what might be going wrong with your setup. What operating system are you using and what version of QGIS are you using? How are you installing it?

**Comment by GeoN5ON** [comment]
Thanks for your response!

I tried it again now and it worked. Sorry!!
