### ISSUE TITLE
Arc wedge and donut creation combined

### ISSUE THREAD

**Issue by fdimaso** [NationalSecurityAgency/qgis-shapetools-plugin#36]
Can the Arc Wedge creation allow the creation of donuts at the same time (i.e. if the file has points where the azimuth is zero and width is 360 deg)?
I've attached a sample pic of what the output would be like.
Thanks
![2021-02-26_17-38-12](https://user-images.githubusercontent.com/55101210/109362658-79740080-7859-11eb-9c8b-60608bcbda70.jpg)

**Comment by hamiltoncj** [comment]
The arc wedge expects a width of less than 360 degrees so it won't work currently as a donut. Is there a reason why you cannot use the donut in that case?

**Comment by fdimaso** [comment]
I just wanted to have both the arc wedges and donut shapes output in a single file.

It’s for building cell towers maps were some sites have antennas that are directional (sectorized – wedge-) while others are omnidirectional (donut shape)

**Comment by hamiltoncj** [comment]
Okay. I will put this on my todo list.

**Comment by hamiltoncj** [comment]
@fdimaso That didn't take too much time to fix so I just added it to Shape Tools 3.3.16. Give it a try and see if it works properly for you.

**Comment by fdimaso** [comment]
Wow, works like a charm. Thanks you so much!!

**Comment by hamiltoncj** [comment]
Great! I am closing the ticket, but if there is another issue please feel free to contact us.
