### ISSUE TITLE
"XY to lines" between the points of a layer fails

### ISSUE THREAD

**Issue by kannes** [NationalSecurityAgency/qgis-shapetools-plugin#37]
I loaded `ne_50m_populated_places.shp` and opened the "XY to line" tool.
There I ticked the "Use the point geometry for the line ending|starting point" boxes.
Processing fails and tells me the features were invalid.

```
{
    "DateLineBreak": False,
    "EndUseLayerGeom": True,
    "EndXField": "",
    "EndYField": "",
    "InputCRS": QgsCoordinateReferenceSystem("EPSG:4326"),
    "InputLayer": "ne_50m_populated_places.shp",
    "LineType": 0,
    "OutputCRS": QgsCoordinateReferenceSystem("EPSG:4326"),
    "OutputLineLayer": "TEMPORARY_OUTPUT",
    "OutputPointLayer": "TEMPORARY_OUTPUT",
    "ShowEndPoint": True,
    "ShowStartPoint": True,
    "StartUseLayerGeom": True,
    "StartXField": "",
    "StartYField": "",
}
```

> 1249 out of 1249 features from the input layer were invalid and were ignored.

**Comment by hamiltoncj** [comment]
@kannes You used the layer geometry for both the start and end of the line. That does not work. You need a beginning and ending point that is not the same point. You need to specify either the beginning or ending or both coordinates from attributes in the table. ne_50m_populated_places.shp does not have such attributes.

I should probably check for this condition and return a clearer error message that the beginning and ending points cannot be the same.

**Comment by kannes** [comment]
Ah, so I cannot use this to make lines between all point pairs of a point layer?

**Comment by hamiltoncj** [comment]
@kannes No it is not for making lines between different point features in a layer. Each feature must include the beginning and ending points. What is the use case for making lines between all point pairs? I don't know if there is an existing capability in QGIS to do that or not.

**Comment by hamiltoncj** [comment]
@kannes I improved the error messages for the XY to Lines tool. I am interested in why you need an algorithm that draws lines between each point. It wouldn't be hard to implement an algorithm like that, but I don't know what the need for it would be.

**Comment by hamiltoncj** [comment]
@kannes Was there anything else you needed with this ticket if not I will go ahead and close it. I added error messages so the user knows not to use the layer geometry for both the beginning and ending points.

**Comment by kannes** [comment]
Thanks! The motivation was about imaginary flight routes between imaginary airports.
