### ISSUE TITLE
idsbreak.svg can't be found on a case-sensitive file system

### ISSUE THREAD

**Issue by kannes** [NationalSecurityAgency/qgis-shapetools-plugin#38]
Error on Linux (case-sensitive filesystem):

`Qt: Cannot open file '/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/shapetools/images/idlbreak.svg', because: No such file or directory`

https://github.com/NationalSecurityAgency/qgis-shapetools-plugin/blob/2e81dea99c76b399648014a5a7533e76f1772813/svg/idlBreak.svg should use a lowercase filename or the references to it https://github.com/NationalSecurityAgency/qgis-shapetools-plugin/search?q=idlbreak should use the camelcase

**Comment by hamiltoncj** [comment]
@kannes Thanks for finding that. That is one of the disadvantages or developing on Windows. I will put out a new release either today or tomorrow.

**Comment by hamiltoncj** [comment]
I just uploaded Shape Tools 3.3.17 so it should be available soon. It should fix this issue.

**Comment by kannes** [comment]
Awesome, thank you for this amazingly swift response.

**Comment by hamiltoncj** [comment]
Thanks for reporting it.
