### ISSUE TITLE
Add Pie Arc Shape

### ISSUE THREAD

**Issue by hamiltoncj** [NationalSecurityAgency/qgis-shapetools-plugin#4]
Parameters:
   Starting Azimuth
   Ending Azimuth
   Inner Radius
   Outer Radius

**Comment by eoparada** [comment]
Hello,

Would it be possible to add a variation of the pie arc shape with input parameters:

Azimuth
Angle Difference
Radius

For example:
Azimuth = 60 deg
Angle Difference = 20 deg
Radius = 1 km

Will draw an arc with 1 km radius from 40 degrees to 80 degrees?  This tool is very useful to plot antenna directions for cellular base stations.  Thanks.

**Comment by hamiltoncj** [comment]
Yes it would be easy to implement this. Are you asking for I pie arc or a pie wedge like is currently implemented? I consider the pie arc to have an inner radius and an outer radius.

**Comment by eoparada** [comment]
The variation request is for the pie wedge.  In that way, I don't need to have a starting and ending angles.  I can base the angle difference on an antenna beamwidth field, for example, and it will plot the wedge depending on how big the beanwidth set on the base station.  Thanks a million.

**Comment by hamiltoncj** [comment]
Just to clarify. If the azimuth is at 60 deg with a beam width of 20 deg then the arc would be plotted from 50 to 70 degrees. Is that correct?

**Comment by eoparada** [comment]
I believe this should be the way, yes.  My bad in my initial example.

**Comment by hamiltoncj** [comment]
@eoparada Version 3.0.8 has an Azimuth mode which will do what you asked. Let me know if this works for you.

**Comment by eoparada** [comment]
Thanks so much @hamiltoncj.  This is what I was looking for.
