### ISSUE TITLE
Unable to remove dropdown buttons from toolbar

### ISSUE THREAD

**Issue by jfbourdon** [NationalSecurityAgency/qgis-shapetools-plugin#42]
Unable to remove dropdown buttons via from toolbar (via Interface Customization) for _Create shapes_, _Geodesic geometry simplification_ and _Geodesic transforms_ tools groups.

Same as [issue #64 for Lat Lon Tools plugin](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/issues/64).

**Comment by hamiltoncj** [comment]
I will look at this later this week. Between holidays and snow days my work load has stacked up.

**Comment by hamiltoncj** [comment]
I released version 3.4.2 that seems to work.

**Comment by hamiltoncj** [comment]
This request should be solved, if there are any further requests please let me know.
