### ISSUE TITLE
Improvement suggestion: Observe QGIS settings for preferred distance units

### ISSUE THREAD

**Issue by beyhh** [NationalSecurityAgency/qgis-shapetools-plugin#43]
The shape tools are really great and I don't want to miss them, especially the geodesic measure tool which should actually be a QGIS standard and not part of a Plugin, but anyway...

The only thing I would suggest is that the measure tool uses the preferred distance unit settings from the QGIS options (Map Tools section) when starting up. Currently, the unit is set to Kilometers by default and I always have to manually select the unit I want.

Other than that, a really great plugin!!!  👍

**Comment by hamiltoncj** [comment]
@beyhh 
I'm glad you like the plugin. This is a very easy change so I updated Shape Tools to version 3.4.3 and made the unit setting persistent so that it will always be what it was last set to.

**Comment by beyhh** [comment]
That's also a good solution and much appreciated. Thank you for the quick response.
