### ISSUE TITLE
Improvement suggestion: provide additional format for azimuth

### ISSUE THREAD

**Issue by beyhh** [NationalSecurityAgency/qgis-shapetools-plugin#44]
I cannot thank the author enough for having brought this wonderful plugin to QGIS!

I would like to suggest another display option for the azimuth in the pop-up window (Heading To / Heading From). It would be wonderful to have an optional format of a 0° - 360° notation. This would suit me and everybody with a maritime background much more. It would be ideal if this setting was persistent as well.

**Comment by hamiltoncj** [comment]
Actually, that option is available. If you go into the settings (Vector->Shape Tools->Settings). There is an option under "Measure Tool Settings" where you can specify the azimuth to be between 0 and 360 and it is persistent.

**Comment by beyhh** [comment]
Oh wow, so cool! Thanks for this hint. Haven't seen this seetings window before...

**Comment by hamiltoncj** [comment]
You raised a good issue. I decided to add a settings icon to the geodesic measure tool that will display the settings dialog box. That should make it easier to realize there are some configuration settings to it. The new version is 3.4.4. I'm going to close this issue.
