### ISSUE TITLE
Minor usability improvement suggestions for Geodesic Measure Tool

### ISSUE THREAD

**Issue by beyhh** [NationalSecurityAgency/qgis-shapetools-plugin#46]
I keep coming back thanking the author for this wonderful plugin! Since I use the Geodesic Measure Tool almost everyday, I have two small improvement suggestions:

1) You can only measure distances as long as the "Geodesic Measure Tool" button is toggled on in the Shape Tools toolbar. It would be nice if the "Geodesic measure tool" toolbar button toggles itself on, when I press the "New" button on the small window displaying the measuring results. I frequently wonder why I cannot draw the measure line and then realize, it's because the toolbar button is not toggled on.

2) Personally, I would would find it more intuitive if pressing the right mouse button was _not_ dropping another measuring point. Instead, the drawing process could just be ended leaving the measure line up to the last point which was set by a **left** mouse button click. 
I regularly get an extra line segment which I didn't actually want because I didn't make up my mind early enough before dropping my last measuring point (which I should have dropped with a right mouse click).

By the way, I noticed that many other toolbars show a tool tip with the toolbar name when hovering over the toolbar itself (not on a button). The _Shape Tools_ and _Lat Lon Tools_ do not show any tooltip. Is that only a feature of QGIS core-toolbars?

**Comment by hamiltoncj** [comment]
Thank you for your suggestions. I think they are all good and will add them to my to-do list. It might take several weeks because I am currently working on another problem.

**Comment by hamiltoncj** [comment]
@beyhh Thank you for these suggestions. I just released version 3.4.5. I think it very much improved how the Geodesic Measure Tool works. I implemented all your suggestions.

**Comment by beyhh** [comment]
Hey, very cool and much faster than expected! 
Glad you appreciate the suggestions. I also think that usability-wise it is an improvement. 

Thank you so much in the name of the QGIS community!!!  👍
