### ISSUE TITLE
Issue with creating pie wedges in Shape Tools for Telecom sectors creation

### ISSUE THREAD

**Issue by anandarupan** [NationalSecurityAgency/qgis-shapetools-plugin#50]
There seems to be a minor challenge in creating sectors (Telecom) using the Pie Wedge option available in Shape Tools plugin. This was working earlier. Below is the snapshot of the inputs provided for creating the same.

![image](https://user-images.githubusercontent.com/119437516/204586483-0ca40feb-2a8c-417f-8798-3564dd62b58f.png)

The resulting output is given below.

![image](https://user-images.githubusercontent.com/119437516/204587214-74c7de66-4f65-4bb6-a0fc-68c8df355ed0.png)

I have been trying to identify if there's a procedural error from my side for quite some days now but finally decided to approach the plugin author and get clarified.

**Comment by hamiltoncj** [comment]
Radius is the distance from the point in terms of the unit radius which you have set to 180 meters. Is your center azimuth and azimuth width in degrees? From your screen shots I cannot tell what you are using for those two parameters other than to know that you are using an expression of some sort. I would need to know what that expression is and what your data looks like.

**Comment by anandarupan** [comment]
Hi, The center azimuth and the azimuth width provided in my input sheet is just an integer value in the CSV file. Since this wasn't working, I also tried providing 2 more columns with beginning azimuth and ending azimuth (delta between the 2 is 30). I assumed that the integer would be populated as degrees format (which was the case earlier when it was working).

Expression 1 (Center Azimuth) snapshot:

![image](https://user-images.githubusercontent.com/119437516/204703326-1619a4b4-fe10-45c0-b2b9-a70b1ce6c0e2.png)

Expression 2 (Azimuth width) snapshot:

![image](https://user-images.githubusercontent.com/119437516/204703398-0edf98b2-1bef-46bd-a69d-83d0cb99d83e.png)

Also, given below is the attribute table showing the columns that are provided in my CSV file.

![image](https://user-images.githubusercontent.com/119437516/204702824-af3f361c-9d65-459a-aeca-5ea5a7800e05.png)

Pls feel free to seek what kind of inputs you would require from me in this subject and I would be glad to provide the same.

**Comment by hamiltoncj** [comment]
As far as I can tell you are doing everything correctly. I made a csv file of just the necessary fields and tried it myself and it worked correctly.  Here is a snapshot.

![image](https://user-images.githubusercontent.com/6978279/204799420-8f849c0e-9f8b-4376-b645-705d0eca0f6f.png)

I've attached the csv file. I guess the next question is what version of qgis are you using and on what operating system? Did you import the csv file as delimited text? I am assuming you did not save it to some other format. Are you using the latest version of the Shape Tools plugin?

[towers.csv](https://github.com/NationalSecurityAgency/qgis-shapetools-plugin/files/10123219/towers.csv)

**Comment by anandarupan** [comment]
Thanks for the feedback. I was also quite surprised as I have worked the same way earlier and it was just fine. I was using QGIS 3.14 (Pi) at that time and still have it. I started working on it again from last 2 weeks and somehow realized that it wasn't working like before. Suspecting that it could be compatibility issue between the plugin and the QGIS version, I had the QGIS version 3.28 (Firenze) installed 2 days back and still it was the same issue (even after uninstalling & reinstalling the plugin in both versions). Shape Tools plugin version also indicates that it is at latest (3.4.9) version.

I am using a Windows 11 OS based Dell machine and was importing the CSV file as a Delimited Text file (which is what I have been doing ever since I have been using QGIS).

**Comment by anandarupan** [comment]
I even tried using the Beginning & End Azimuth option with separate columns added in my input CSV file for those in addition to Center Azimuth & Beamwidth.

![image](https://user-images.githubusercontent.com/119437516/204809043-e28a1ae9-4f58-4975-a2c8-a903a329156d.png)

Beginning Azimuth detail snapshot:

![image](https://user-images.githubusercontent.com/119437516/204808735-74eaa36b-acec-4906-8c8d-f8edccc5ad9b.png)

Ending Azimuth detail snapshot:

![image](https://user-images.githubusercontent.com/119437516/204808948-571abc51-9520-4a45-8451-02bcc460a527.png)

**Comment by anandarupan** [comment]
The resulting output is given below if I use the Beginning & Ending Azimuth options.

![image](https://user-images.githubusercontent.com/119437516/204809700-21a0f136-74e0-4475-9bdf-f85f7b320559.png)

**Comment by hamiltoncj** [comment]
Can you try the towers.csv file that I attached above and see if you get my results or something different? I don't have Windows 11 to test. Has this worked in the past with Windows 11? Is it possible to share your csv file or at least a portion that is exhibiting this behavior? I really don't know what is wrong at this point. Could you open up your python console "Plugins->Python Console" and type in these two commands and send me the results? I've never had an issue with this so I don't think there will be a problem.

import geographiclib
geographiclib.\_\_version\_\_

**Comment by anandarupan** [comment]
I tried with the CSV file that you shared with the same set of Center Azimuth & Beamwidth selections but there is no change in the output. I am still getting just like how I raised in my 1st post.

![image](https://user-images.githubusercontent.com/119437516/204817518-7134d2b7-406b-4bae-a5e9-d2519d86cf81.png)

I will share a portion of the CSV file which I have been using with you to see if you are also getting similar issue. Then, we would be able to identify if the issue is with the input CSV file.

[QGIS Sample Input.csv](https://github.com/NationalSecurityAgency/qgis-shapetools-plugin/files/10123939/QGIS.Sample.Input.csv)

**Comment by anandarupan** [comment]
Below is the snapshot of the commands output from the python console as you requested

![image](https://user-images.githubusercontent.com/119437516/204818576-0ee6bb5b-0535-4ca6-beea-769ef1f31ee6.png)

**Comment by hamiltoncj** [comment]
We have something strange going on. If you use the Assistant it fails in the way you have shown, but if you just select the field from "Field type" it works. I don't know if this is a QGIS bug or whether there is a difference in using the assistant. Once selected from "Field type" and then you look at it with Assistant, I see no differences.

![image](https://user-images.githubusercontent.com/6978279/204826002-64984f3a-96d8-4634-a2d7-0119d33b1cff.png)

**Comment by anandarupan** [comment]
Thank you for the quick identification. I tried it the way you suggested, it just works like before. Pls have a look below at the output which I have been trying to get for the past 2 weeks. Thank you very much for the prompt response and resolution.

![image](https://user-images.githubusercontent.com/119437516/204827238-ea7f7454-d468-4358-afd7-41f3e7dab871.png)

However, I noticed that there is a catch. After selecting the field "Azimuth" & "Beamwidth" through the "Field Type" option, if we click on Assistant (just to confirm if it is indeed the same as what we chose), the output again gets rendered the way I shared in my initial post. Ideally, we should just choose from the Field type and then execute the vector creation.

**Comment by hamiltoncj** [comment]
I will investigate the Assistant and see if I can figure anything out. Both methods should give the same results. I will put in a QGIS ticket if it appears to be their problem.

**Comment by anandarupan** [comment]
Great, thanks for the feedback. Just now, another colleague got in touch with me with the same problem and he was surprised with the immediate fix which you had suggested. I will proceed to close this ticket if that is fine with you!

**Comment by hamiltoncj** [comment]
Go ahead and close it.

**Comment by hamiltoncj** [comment]
I took a closer look at the Assistant and it validates the input and output values. For example the Output 'from' and 'to' default to 1 and 10 so any output value less than 1 is set to 1 and any value greater than 10 is set to 10. That is way it was giving the wrong results. To use the assistant for this case you would need to set the Output 'from' and 'to' to -360 and 360 or possibly just 0 and 360 if the azimuth and beamwidth are never negative.

I'm not sure what the Input 'from' and 'to' does.
