### ISSUE TITLE
User info suggestion

### ISSUE THREAD

**Issue by andre-kotze** [NationalSecurityAgency/qgis-shapetools-plugin#52]
Great plugin. I have tried to use Geodesic Densify on line layers with geometry type LineStringZ. The fact that it doesn't work is no issue at all, but it only says "{} of {} features failed to process correctly" and outputs an empty polygon layer. I think it would be better with a more informative error message...

**Comment by hamiltoncj** [comment]
@andre-kotze I have fixed that problem and released a new version; however, the output layer will either be a LineString, MultiLineString, Polygon, or MultiPolygon layer. I am not retaining the Z or M values because I don't think it makes sense to interpolate them.

**Comment by andre-kotze** [comment]
Thanks! And I totally agree.
