### ISSUE TITLE
contour line free hand design 

### ISSUE THREAD

**Issue by marcscama** [NationalSecurityAgency/qgis-shapetools-plugin#53]
hi, i try the plugin and it works with point. i looking for something to draw contour lines by hand but with a little bit assisted with elliptical shape, for exmple i draw the axes of the ellipse and the plugin draw the rest of the ellipse.
thanks

**Comment by hamiltoncj** [comment]
QGIS has a native "Shape Digitizing Toolbar" to interactively draw shapes. You will probably have to enable it to see it in your toolbar area. I would Google it to learn how to use it. I don't have any tools with my plugins that would help you with what you are describing.

**Comment by hamiltoncj** [comment]
I am going to close this because it doesn't have anything to do with this plugin. Here are some locations where you might be able to ask questions and get more help. https://qgis.org/en/site/forusers/support.html
