### ISSUE TITLE
Create radial lines generates empty dataset

### ISSUE THREAD

**Issue by GustyLa** [NationalSecurityAgency/qgis-shapetools-plugin#54]
The function "Create radial lines" generates empty datasets. I have tried this with different coordinate systems, as well as temporary and permanent layers, but with the same result. The other functions work, so the issue seems to be isolated to this specific function. Log:

QGIS version: 3.28.15-Firenze
QGIS code revision: 252ad49ddc
Qt version: 5.15.3
Python version: 3.9.18
GDAL version: 3.8.3
GEOS version: 3.12.1-CAPI-1.18.1
PROJ version: Rel. 9.3.1, December 1st, 2023
PDAL version: 2.6.0 (git-version: 3fced5)
Algorithm started at: 2024-04-05T09:50:50
Algorithm 'Create radial lines' starting…
Input parameters:
{ 'ExportInputGeometry' : False, 'INPUT' : 'memory://Point?crs=EPSG:25832&field=Drawings:string(255)&uid={e70cc898-4331-4678-a0cb-16cda44afab7}', 'InnerRadius' : 10, 'NumberOfLines' : 5, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OuterRadius' : 20, 'UnitsOfMeasure' : 1 }

1 out of 1 features had invalid parameters and were ignored.
Execution completed in 0.01 seconds
Results:
{'OUTPUT': 'Output_layer_f84f7869_0b33_4e9d_b06a_5c94420ed704'}

Loading resulting layers
Algorithm 'Create radial lines' finished

**Comment by hamiltoncj** [comment]
Thanks for bringing this to my attention. I put out a new release, version 3.4.19 that should have fixed it. At least it is working with my testing. Let me know if you have any other problems.

**Comment by GustyLa** [comment]
Works great! Thanks for the update!

**Comment by hamiltoncj** [comment]
Fixed.
