### ISSUE TITLE
Telecom Site Sector creation

### ISSUE THREAD

**Issue by uppalavamsi** [NationalSecurityAgency/qgis-shapetools-plugin#9]
Telecom site plan and optimization using QGIS

Request to please prioritize the layer order by size of shape in Pie Wedge (least size should be overlay onto its next size such that all layers are visible) when we sketch the vector using same point and size is different of each layer. Such that all layers are visible without submerge.
[Telecom.zip](https://github.com/NationalSecurityAgency/qgis-shapetools-plugin/files/1907880/Telecom.zip)

https://twitter.com/vamsi_uppala/status/984504617215049728

![image](https://user-images.githubusercontent.com/38352200/38741973-e2cd0834-3f58-11e8-85c3-93b153b72324.png)

![image](https://user-images.githubusercontent.com/38352200/38742029-0c0a5846-3f59-11e8-84ce-788f67b5bc8a.png)

![image](https://user-images.githubusercontent.com/38352200/38735696-2cf5d452-3f47-11e8-80f1-5c121a358788.png)
![telecom site cells sectors](https://user-images.githubusercontent.com/38352200/38735803-945e4afc-3f47-11e8-8dd2-b95bc57b6740.gif)
![telecom site sectors](https://user-images.githubusercontent.com/38352200/38735828-ad09e8cc-3f47-11e8-848e-88dd25620818.gif)
![making sectors](https://user-images.githubusercontent.com/38352200/38735854-b695887e-3f47-11e8-81c6-71e9acfc3ee3.gif)

![image](https://user-images.githubusercontent.com/38352200/38734599-d3df3140-3f43-11e8-9953-7068c9520c27.png)

**Comment by hamiltoncj** [comment]
@uppalavamsi I believe the proper way to do this is not in the plugin, but with styling. The order that you want may be different from what someone else would want and there may be other calculations used that another person would want to use to affect rendering order. I think it would be difficult to guess all the possible ways users would want to do this, but QGIS already has the mechanisms in place to control the rendering order.

It is very easy to change the rendering order. Right mouse click on the Shape Tools output layer and select Properties. Select the 'Style' tab on the left. On the top select 'Categorized.' For the 'Column' choose 'Antenna Height' from your sample data set. Click on the 'Classify' button. Towards the bottom check the box that says "Control feature rendering order." To the far right of this check box click on the A/Z down arrow check box. A new pop up will be displayed. For the expression select the 'Antenna Height' field and 'Descending' order. The net result of all this is what you want.

![exmple1](https://user-images.githubusercontent.com/6978279/38819459-724b185e-4169-11e8-8380-3513c78a4899.jpg)

![exmple2](https://user-images.githubusercontent.com/6978279/38819482-851cb9ce-4169-11e8-8092-0158505e3510.jpg)

![exmple3](https://user-images.githubusercontent.com/6978279/38819491-8d530058-4169-11e8-8c3c-71272f4348f4.jpg)

**Comment by uppalavamsi** [comment]
Hi Hamilton,

Thanks so much for let us know the detailed approach on rendering process,
i feel i could have done more self study on tool before writing it.

But thanks very for you time and letting us know the process step by step.

With regards,
Vamsi
+91 98 664 68185
